### ISSUE TITLE
Tab problems

### ISSUE THREAD

**Issue by joepan** [wpexplorer/symple-shortcodes#2] opened 2016-05-31 00:49 UTC
The Wordpress update in late-April/early-May broke the tab function on my site: http://www.brooklynartspress.com/portfolio/take-this-stallion-by-anais-duplan/.

Instead of opening a new tab, clicking the tab button takes you to the corresponding text further down the page. I thought perhaps the shortcode for tabs had changed, but it did not, as far as I could tell. I tried deactivating all other plugins, but nothing helped.

Thank you for taking the time to look into my issue!

**Comment by wpexplorer** [comment] 2016-05-31 00:50
Hi @joepan - The error is being caused by the theme by a javascript error which was fixed in the update from May 15 - http://www.wpexplorer.com/changelogs/adapt/ - If you can please re-download and update the theme manually via FTP. I also added automatic updates so in the future you will receive a notice in your WP dashboard as well as the adapt theme now has all the premium features (customizer styling options and auto updates) included in the Free version ;)

Please let me know if you still have issues after updating!
- AJ

**Comment by wpexplorer** [comment] 2016-05-31 00:50
Oh here is the download page: http://www.wpexplorer.com/adapt-free-responsive-wordpress-theme/

**Comment by joepan** [comment] 2016-05-31 00:57
I had a professional help me with the theme, & I believe he made some changes. I run a publishing company with many daily hits. If I reupload the theme & it breaks the site, I'm losing a lot of money. I would be terrified to update the whole theme. Is there a specific line of code or something I can plug-in somewhere to fix the tabs?

**Comment by wpexplorer** [comment] 2016-05-31 01:48
If you hired a professional then all tweaks should have been made via a child theme and updating the core theme shouldn't break anything ;)

There were a lot of good updates made...but I understand your concern. If you need to fix just this issue re-download and locate the file at js/global.js and you need to fix the back to top part to use a class instead (compare to your file). And update the back to top link in the footer.php file to have the classname "scroll-top" to match the updated global.js file.

**Closed as completed** 2016-08-12 01:29 UTC
